name: Update GitHub Stats in README

on:
  schedule:
    - cron: "0 */6 * * *"  # Her 6 saatte bir çalışır
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Depoyu Klonla
        uses: actions/checkout@v3

      - name: README Güncelle
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          curl -o README.md "https://github-readme-stats.vercel.app/api?username=rcptok25&show_icons=true&theme=radical&include_all_commits=true&count_private=true"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "📊 Update GitHub Stats (Automated)"
          git push
