name: Update GitHub Stats in README

on:
  schedule:
    - cron: "0 */6 * * *"  # Her 6 saatte bir çalışır
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Depoyu Klonla
        uses: actions/checkout@v3

      - name: GitHub Stats'leri Güncelle
        uses: anuraghazra/github-readme-stats@master
        with:
          username: rcptok25
          show_icons: true
          theme: radical
          include_all_commits: true
          count_private: true
          token: ${{ secrets.GH_PAT }}

      - name: README Dosyasını Güncelle
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "📊 Update GitHub Stats (Automated)"
          git push
